apiVersion: v1
kind: Pod
metadata:
  name: {pod_name}
  namespace: {namespace}
spec:
  restartPolicy: Never
  containers:
  - name: buildkit
    image: moby/buildkit:latest
    securityContext:
      privileged: true
    command: ["/bin/sh"]
    args:
    - -c
    - |
      set -e
      echo "Pod ready, waiting for build context..."
      
      # Wait for build context to be uploaded via kubectl cp
      while [ ! -f /build-context/BUILD_READY ]; do
        echo "Waiting for build context upload..."
        sleep 2
      done
      
      echo "Build context received, starting BuildKit daemon..."
      buildkitd --addr unix:///run/buildkit/buildkitd.sock --oci-worker=true --containerd-worker=false &
      
      # Wait for daemon
      for i in $(seq 1 30); do
        if [ -S /run/buildkit/buildkitd.sock ]; then
          echo "BuildKit daemon ready"
          break
        fi
        echo "Waiting for BuildKit daemon... ($i/30)"
        sleep 2
      done
      
      if [ ! -S /run/buildkit/buildkitd.sock ]; then
        echo "Failed to start BuildKit daemon"
        exit 1
      fi
      
      echo "Build context contents:"
      ls -la /build-context/
      
      # Build multiplatform image
      echo "Building multiplatform image: {image_name}"
      buildctl --addr unix:///run/buildkit/buildkitd.sock build \
        --progress=plain \
        --frontend=dockerfile.v0 \
        --local context=/build-context \
        --local dockerfile=/build-context \
        --output type=image,name={image_name},push=true \
        --opt platform=linux/amd64,linux/arm64
    volumeMounts:
    - name: build-context
      mountPath: /build-context
    - name: docker-config
      mountPath: /root/.docker
  volumes:
  - name: build-context
    emptyDir: {{}}
  - name: docker-config
    secret:
      secretName: {secret_name}
      items:
      - key: .dockerconfigjson
        path: config.json